<a href="https://colab.research.google.com/github/1546329G/python_pyt/blob/main/ejerciico_recuerdos16_9_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#fundamentos de vectores y matrices
import numpy as np


#crear vector
vector = np.array([1,2,3,4,5])
#print(vector)

#crear matriz
matriz=np.array([[1,2,3,],[4,5,6]])
#print(matriz)

#opreaciones  basicas
suma_vector = vector+3
print(suma_vector)
#print(suma_vector)
producto_m_v = np.dot(matriz,vector[:3])
print(producto_m_v)


[4 5 6 7 8]
[14 32]


In [12]:
#jerciio 1 crear un vector de tamaño 10 con valores del 1 al 10 crea una
#matriz de tamaño 3x3 con valores del 1 al 9 realiza la multiplicacion de la matriz con el vector


#forma 1
import numpy as np
#crear vector
vector = np.array([1,2,3,4,5,6,7,8,9,10])
#crear matriz
matriz=np.array([[1,2,3,],[4,5,6],[7,8,9]])
#opreaciones  basicas
producto_m_v = np.dot(matriz,vector[:3])
print(producto_m_v)




#forma2
import numpy as np
#crear vector con rango
vector = np.arange(1,11) #si inicia en 1 y termina en 10
#crear matriz con rango
matriz=np.arange(1,10).reshape(3,3) #inicia n 1 y termina en 9 /f=3 c=3
vector_truncado = vector[6:9]
producto_m_v = np.dot(matriz,vector_truncado)
print(producto_m_v)

[14 32 50]
[ 50 122 194]


In [1]:
#pandas : libreria de python para manupular y analyzar datos /dataframe
#numpys ?: libreria de python para realizar calculos cientificos/ arreglos multiplicacon
import pandas as pd
import numpy as np
# dataframe usar pandas
data={'columna1': [100,200,300],'columna2':[10.5,20.5,30.5]}
df = pd.DataFrame(data)
print(df)

#operaciones comn pandas y numpys
df['columna3']=np.log(df['columna2'])
print(df)

   columna1  columna2
0       100      10.5
1       200      20.5
2       300      30.5
   columna1  columna2  columna3
0       100      10.5  2.351375
1       200      20.5  3.020425
2       300      30.5  3.417727


CREA UNA DATA FRAME CON 5 FILAS Y 3 COLUMAS
DE DAROS ALEATORIOS, AÑADE UNA COLUMNA CALCULANDO LA SUMA DE LAS 2 PRIMERAS  COLUMNAS

In [8]:
import pandas as pd
import numpy as np
# dataframe usar pandas
data={'columna1': [100,200,300,400,500],'columna2':[10.5,20.5,30.5,4.5,7.6]}
df = pd.DataFrame(data)
print(df)


#operaciones comn pandas y numpys, SUMA DE COLUMNAS
df['columna3'] = df['columna1'] + df['columna2']
print(df)

   columna1  columna2
0       100      10.5
1       200      20.5
2       300      30.5
3       400       4.5
4       500       7.6
   columna1  columna2  columna3
0       100      10.5     110.5
1       200      20.5     220.5
2       300      30.5     330.5
3       400       4.5     404.5
4       500       7.6     507.6


In [9]:
#MANIPULACION Y NANALISIS DE ESTRUTURA DE  DATOS

data={'Nombre':['chaly','Carolina','German'],'Edad':[30,28,89]}
df=pd.DataFrame(data)
#flitardo de datos
df_filtrado = df[df['Edad']>=30]
print("\nFiltrado de datos por edad ")
print(df_filtrado)


Filtrado de datos por edad 
   Nombre  Edad
0   chaly    30
2  German    89


ejercicio 3: CREAR UNA DATAFRAME CON INFORMACION DE ESTUDIANTES DE SENATI, DONDE TENDRAS:
NOMBRE,EDAD,CARRERA,NOTAFINAL,DBERAS CREAR MINIMO 6 REGISTROS MAXIMO 12, FLITRAR POR LAS CARRERAS QUE TENGAN LA MAYOR NOTA

In [4]:
#ejercicio 3

import pandas as pd
import numpy as np
# dataframe usar pandas
data={'columna1': ['NOMBRE','EDAD','CARRERA','NOTALFINAL'],'columna2':[10.5,20.5,30.5,4.5]}
df = pd.DataFrame(data)
print(df)






   Nombre  Edad     Carrera  NotaFinal
0    Juan    20  Ingenieria         16
1   Pedro    22    Medicina         18
2   Maria    21     Derecho         17
3     Ana    19  Ingenieria         19
4    Luis    23    Medicina         15
5  Carmen    20     Derecho         17
Carrera
Derecho       17
Ingenieria    19
Medicina      18
Name: NotaFinal, dtype: int64


In [7]:

import pandas as pd

data={
  'Nombre' : ['Gandy','carolina','hulk','steve','jorge','karen'],
  'edad': [18,43,31,18,45,89],
  'carrera':['fisica','matemaricas','cosineroi','valet','derecho','sicologo'],
  'Notafinal':[11,17,15,14,78,56]

}

df=pd.DataFrame(data)
#flitrado de datos de la nota maxima
notaMaxima = df['Notafinal'].max()
df_filtrado = df[df['Notafinal']==notaMaxima]
print("\nFiltrado de datos por nota ")
print(df_filtrado)











Filtrado de datos por nota 
  Nombre  edad  carrera  Notafinal
4  jorge    45  derecho         78
     Nombre  edad       carrera  Notafinal
0     Gandy    18       sofware         11
1  carolina    43  Electricidad         17
2      hulk    31        textil         15
3     steve    18       sofware         14
4     jorge    45  Electricidad         78
5     karen    89        textil         56
     Nombre  edad       carrera  Notafinal
0     Gandy    18       sofware         11
1  carolina    43  Electricidad         17
2      hulk    31        textil         15
3     steve    18       sofware         14
4     jorge    45  Electricidad         78
5     karen    89        textil         56


In [12]:
#crear archicos CSV
import pandas as pd
import numpy as np

data={
     'Nombre' : ['Gandy','carolina','hulk','steve','jorge','karen'],
    'edad': [18,43,31,18,45,89],
   'carrera':['sofware','Electricidad','textil','sofware','Electricidad','textil'],
   'Notafinal':[11,17,15,14,78,56]
 }
df=pd.DataFrame(data)
#guardamos los datos en un archivo csv
df.to_csv('estudiantes_senati.csv',index=False)

#LEEER EL ARCHIVO CSV Y LEERLOS PARA EL ANALIZIS
df_leido=pd.read_csv('estudiantes_senati.csv')
print(df_leido)
#leer el archivo cssv con numpy
data_np=np.genfromtxt('estudiantes_senati.csv',delimiter=',',dtype=None,encoding='utf8',names=True)
print(df_leido)


     Nombre  edad       carrera  Notafinal
0     Gandy    18       sofware         11
1  carolina    43  Electricidad         17
2      hulk    31        textil         15
3     steve    18       sofware         14
4     jorge    45  Electricidad         78
5     karen    89        textil         56
     Nombre  edad       carrera  Notafinal
0     Gandy    18       sofware         11
1  carolina    43  Electricidad         17
2      hulk    31        textil         15
3     steve    18       sofware         14
4     jorge    45  Electricidad         78
5     karen    89        textil         56


CREAR un archivo csv c con datos de producto, cantidad, precio_unitario_docena_valor_venta,yluego mostrarlos por pandas y numpys

In [23]:

# Importa las bibliotecas necesarias
import pandas as pd
import numpy as np

# Crea un diccionario con los datos
data = {
    'producto': ['manzana', 'banana', 'naranja', 'uva', 'pera'],
    'cantidad': [10, 15, 12, 8, 20],
    'precio-unitario-docena': [12, 6, 9, 15, 10],
    'valor-venta': [120, 90, 108, 120, 900]
}

df = pd.DataFrame(data)
df.to_csv('productos.csv', index=False)
df_pandas = pd.read_csv('productos.csv')
print("Datos con pandas:")
print(df_pandas)





Datos con pandas:
  producto  cantidad  precio-unitario-docena  valor-venta
0  manzana        10                      12          120
1   banana        15                       6           90
2  naranja        12                       9          108
3      uva         8                      15          120
4     pera        20                      10          900


#MACHIE LEARNING

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data=load_iris()